analysis_name: 'Metagenomics DEFAULT'

# File Specifications
contigs: "tests/fasta_files"
extension: "fasta"
verified_contigs: "tests/fasta_files_verified"
contig_db: "tests/contig_dbs"

# Databases
cazyme_db: "dbs/CAZyme/"
cazyme_mapper: "dbs/CAZyme/fam-substrate-mapping-08252022.tsv"
tigrfam_db: "dbs/TigrFams/AllTigrHmms.hmm"
tigrfam_roles: "dbs/TigrFams/TFAM-Roles.txt"

# Computing
threads: 80

# Logging
log_id: "AnnotatingMAGs DEFAULT"
database_name: "DEFAULT Database Name"