package:
  name: genome-annotator
  version: "1.0.0"

source:
  git_rev: "1.0"
  git_url: https://github.com/ddeemerpurdue/genome-annotator.git

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - genome-annotator

about:
  home: https://github.com/ddeemerpurdue/genome-annotator
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
